version: '3.8'

services:
  vuepress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    volumes:
      - .:/app
    networks:
      - webnet

networks:
  webnet: