services:
  blog_plus: # 服务名称
    image: weijordan/blog_plus # 镜像名称
    container_name: blog_plus # 容器名称
    build: .
    ports:
      - "3002:80"  # 将容器的 80 端口映射到宿主机的 3002 端口
    # environment:
    #   - VIRTUAL_HOST=weijordan.com,www.weijordan.com,blog.weijordan.com  # 替换为您的域名，用逗号分隔
    #   - LETSENCRYPT_HOST=weijordan.com,www.weijordan.com,blog.weijordan.com  # 替换为您的域名
    #   - LETSENCRYPT_EMAIL=1985615319@qq.com  # 替换为您的邮箱
    restart: unless-stopped # 容器退出时总是重启
    networks:
      - webnet

networks:
  webnet:
