# version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - ACME_EMAIL=1985615319@qq.com  # 替换为您的邮箱
    networks:
      - webnet

  blog_plus: # 服务名称
    image: weijordan/blog_plus:latest # 镜像名称
    container_name: blog_plus # 容器名称
    ports:
      - "3002:80"  # 将容器的80端口映射到宿主机的8080端口
    volumes:
      - /myDocker/blog_plus:/app  # 将宿主机的/data/blog_plus目录映射到容器内的/app目录
    environment:
      - VIRTUAL_HOST=weijordan.com,www.weijordan.com,blog.weijordan.com  # 替换为您的域名，用逗号分隔
      - LETSENCRYPT_HOST=weijordan.com,www.weijordan.com,blog.weijordan.com  # 替换为您的域名
      - LETSENCRYPT_EMAIL=1985615319@qq.com  # 替换为您的邮箱
    restart: unless-stopped # 容器退出时总是重启
    networks:
      - webnet

networks:
  webnet:

  # 运行容器
  # docker-compose up -d
  # 检查运行情况
  # docker-compose ps
  # 停止并移除容器
  # docker-compose down
  # 停止容器
  # docker-compose stop
  # 启动容器
  # docker-compose start
  # 重启容器
  # docker-compose restart
